name: CI

on: 
  push:
    branches: [ "testing" ]

  workflow_dispatch:

jobs:  
  build:   
    runs-on: ubuntu-latest

    steps:
      - name: "Mostrar un mensaje"
        run: echo "Hello, world!"
